backend:
  name: github
  repo: astral_hand
  branch: netlifly_cms
media_folder: "assets"
collections:
  - name: "media"
    label: "Media Item"
    folder: "_media"
    fields:
      - {label: "Title", name: "Title"}
